# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LuciaboMinimal
email: lucianoeduardo@live.com
description: > # this means to ignore newlines until "baseurl:"
  Este é um blog minimalista criado para aprender como
  funciona a linda e fofa ferramenta chamada Jekyll
baseurl: "/luciabominimal" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: luscisno
github_username:  luciamo

# Build settings
markdown: kramdown
permalink: /:title
